# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_clans_info200_response import GetClansInfo200Response

class TestGetClansInfo200Response(unittest.TestCase):
    """GetClansInfo200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClansInfo200Response:
        """Test GetClansInfo200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClansInfo200Response`
        """
        model = GetClansInfo200Response()
        if include_optional:
            return GetClansInfo200Response(
                status = 'error',
                meta = wot_api_client.models.clans_info_meta.clans_info_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.clans_info_data_value.clans_info_data_value(
                        clan_id = 56, 
                        name = '', 
                        tag = '', 
                        created_at = 56, 
                        color = '', 
                        members_count = 56, 
                        emblems = wot_api_client.models.clans_list_data_inner_emblems.clans_list_data_inner_emblems(
                            x24 = {
                                'key' : ''
                                }, 
                            x32 = {
                                'key' : ''
                                }, 
                            x64 = {
                                'key' : ''
                                }, 
                            x195 = {
                                'key' : ''
                                }, 
                            x256 = {
                                'key' : ''
                                }, ), 
                        old_name = '', 
                        old_tag = '', 
                        renamed_at = 56, 
                        description = '', 
                        description_html = '', 
                        motto = '', 
                        is_clan_disbanded = True, 
                        accepts_join_requests = True, 
                        updated_at = 56, 
                        creator_id = 56, 
                        creator_name = '', 
                        leader_id = 56, 
                        leader_name = '', 
                        members = null, 
                        private = wot_api_client.models.clans_info_data_value_private.clans_info_data_value_private(
                            treasury = 56, 
                            clan_treasury = wot_api_client.models.clans_info_data_value_private_clan_treasury.clans_info_data_value_private_clan_treasury(
                                gold = 56, 
                                credits = 56, 
                                crystal = 56, ), 
                            online_members = [
                                56
                                ], ), )
                    },
                error = wot_api_client.models.error.error()
            )
        else:
            return GetClansInfo200Response(
                status = 'error',
                meta = wot_api_client.models.clans_info_meta.clans_info_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.clans_info_data_value.clans_info_data_value(
                        clan_id = 56, 
                        name = '', 
                        tag = '', 
                        created_at = 56, 
                        color = '', 
                        members_count = 56, 
                        emblems = wot_api_client.models.clans_list_data_inner_emblems.clans_list_data_inner_emblems(
                            x24 = {
                                'key' : ''
                                }, 
                            x32 = {
                                'key' : ''
                                }, 
                            x64 = {
                                'key' : ''
                                }, 
                            x195 = {
                                'key' : ''
                                }, 
                            x256 = {
                                'key' : ''
                                }, ), 
                        old_name = '', 
                        old_tag = '', 
                        renamed_at = 56, 
                        description = '', 
                        description_html = '', 
                        motto = '', 
                        is_clan_disbanded = True, 
                        accepts_join_requests = True, 
                        updated_at = 56, 
                        creator_id = 56, 
                        creator_name = '', 
                        leader_id = 56, 
                        leader_name = '', 
                        members = null, 
                        private = wot_api_client.models.clans_info_data_value_private.clans_info_data_value_private(
                            treasury = 56, 
                            clan_treasury = wot_api_client.models.clans_info_data_value_private_clan_treasury.clans_info_data_value_private_clan_treasury(
                                gold = 56, 
                                credits = 56, 
                                crystal = 56, ), 
                            online_members = [
                                56
                                ], ), )
                    },
                error = wot_api_client.models.error.error(),
        )
        """

    def testGetClansInfo200Response(self):
        """Test GetClansInfo200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
