# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.api.clans_api import ClansApi


class TestClansApi(unittest.TestCase):
    """ClansApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClansApi()

    def tearDown(self) -> None:
        pass

    def test_get_clans_accountinfo(self) -> None:
        """Test case for get_clans_accountinfo

        Clan member details
        """
        pass

    def test_get_clans_glossary(self) -> None:
        """Test case for get_clans_glossary

        Clan glossary
        """
        pass

    def test_get_clans_info(self) -> None:
        """Test case for get_clans_info

        Clan details
        """
        pass

    def test_get_clans_list(self) -> None:
        """Test case for get_clans_list

        Clans
        """
        pass

    def test_get_clans_memberhistory(self) -> None:
        """Test case for get_clans_memberhistory

        Player's clan history
        """
        pass

    def test_get_clans_messageboard(self) -> None:
        """Test case for get_clans_messageboard

        Message board
        """
        pass


if __name__ == '__main__':
    unittest.main()
