# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.globalmap_claninfo_ok import GlobalmapClaninfoOk

class TestGlobalmapClaninfoOk(unittest.TestCase):
    """GlobalmapClaninfoOk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalmapClaninfoOk:
        """Test GlobalmapClaninfoOk
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalmapClaninfoOk`
        """
        model = GlobalmapClaninfoOk()
        if include_optional:
            return GlobalmapClaninfoOk(
                status = 'ok',
                meta = wot_api_client.models.globalmap_claninfo_meta.globalmap_claninfo_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.globalmap_claninfo_data_value.globalmap_claninfo_data_value(
                        clan_id = 56, 
                        tag = '', 
                        name = '', 
                        statistics = wot_api_client.models.globalmap_claninfo_data_value_statistics.globalmap_claninfo_data_value_statistics(
                            battles = 56, 
                            wins = 56, 
                            losses = 56, 
                            battles_10_level = 56, 
                            battles_8_level = 56, 
                            battles_6_level = 56, 
                            wins_10_level = 56, 
                            wins_8_level = 56, 
                            wins_6_level = 56, 
                            captures = 56, 
                            provinces_count = 56, ), 
                        ratings = wot_api_client.models.globalmap_claninfo_data_value_ratings.globalmap_claninfo_data_value_ratings(
                            updated_at = 56, 
                            elo_6 = 56, 
                            elo_8 = 56, 
                            elo_10 = 56, ), 
                        private = wot_api_client.models.globalmap_claninfo_data_value_private.globalmap_claninfo_data_value_private(
                            daily_wage = 56, 
                            influence = 56, ), )
                    }
            )
        else:
            return GlobalmapClaninfoOk(
                status = 'ok',
                meta = wot_api_client.models.globalmap_claninfo_meta.globalmap_claninfo_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.globalmap_claninfo_data_value.globalmap_claninfo_data_value(
                        clan_id = 56, 
                        tag = '', 
                        name = '', 
                        statistics = wot_api_client.models.globalmap_claninfo_data_value_statistics.globalmap_claninfo_data_value_statistics(
                            battles = 56, 
                            wins = 56, 
                            losses = 56, 
                            battles_10_level = 56, 
                            battles_8_level = 56, 
                            battles_6_level = 56, 
                            wins_10_level = 56, 
                            wins_8_level = 56, 
                            wins_6_level = 56, 
                            captures = 56, 
                            provinces_count = 56, ), 
                        ratings = wot_api_client.models.globalmap_claninfo_data_value_ratings.globalmap_claninfo_data_value_ratings(
                            updated_at = 56, 
                            elo_6 = 56, 
                            elo_8 = 56, 
                            elo_10 = 56, ), 
                        private = wot_api_client.models.globalmap_claninfo_data_value_private.globalmap_claninfo_data_value_private(
                            daily_wage = 56, 
                            influence = 56, ), )
                    },
        )
        """

    def testGlobalmapClaninfoOk(self):
        """Test GlobalmapClaninfoOk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
