# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_encyclopedia_personalmissions200_response_one_of_data_value_operations_value_missions_value import GetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue

class TestGetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue(unittest.TestCase):
    """GetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue:
        """Test GetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue`
        """
        model = GetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue()
        if include_optional:
            return GetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue(
                mission_id = 56,
                set_id = 56,
                name = '',
                description = '',
                hint = '',
                min_level = 56,
                max_level = 56,
                tags = [
                    ''
                    ],
                rewards = {
                    'key' : wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value_operations_value_missions_value_rewards_value.get_encyclopedia_personalmissions_200_response_oneOf_data_value_operations_value_missions_value_rewards_value(
                        conditions = '', 
                        credits = 56, 
                        items = {
                            'key' : 56
                            }, 
                        premium = 56, 
                        free_xp = 56, 
                        tokens = 56, 
                        slots = 56, 
                        berths = 56, )
                    }
            )
        else:
            return GetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue(
                mission_id = 56,
                set_id = 56,
                name = '',
                description = '',
                hint = '',
                min_level = 56,
                max_level = 56,
                tags = [
                    ''
                    ],
                rewards = {
                    'key' : wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value_operations_value_missions_value_rewards_value.get_encyclopedia_personalmissions_200_response_oneOf_data_value_operations_value_missions_value_rewards_value(
                        conditions = '', 
                        credits = 56, 
                        items = {
                            'key' : 56
                            }, 
                        premium = 56, 
                        free_xp = 56, 
                        tokens = 56, 
                        slots = 56, 
                        berths = 56, )
                    },
        )
        """

    def testGetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue(self):
        """Test GetEncyclopediaPersonalmissions200ResponseOneOfDataValueOperationsValueMissionsValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
