# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.account_achievements_ok import AccountAchievementsOk

class TestAccountAchievementsOk(unittest.TestCase):
    """AccountAchievementsOk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountAchievementsOk:
        """Test AccountAchievementsOk
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountAchievementsOk`
        """
        model = AccountAchievementsOk()
        if include_optional:
            return AccountAchievementsOk(
                status = 'ok',
                meta = wot_api_client.models.account_achievements_meta.account_achievements_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.account_achievements_data_value.account_achievements_data_value(
                        achievements = {
                            'key' : 56
                            }, 
                        max_series = {
                            'key' : 56
                            }, 
                        frags = {
                            'key' : 56
                            }, )
                    }
            )
        else:
            return AccountAchievementsOk(
                status = 'ok',
                meta = wot_api_client.models.account_achievements_meta.account_achievements_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.account_achievements_data_value.account_achievements_data_value(
                        achievements = {
                            'key' : 56
                            }, 
                        max_series = {
                            'key' : 56
                            }, 
                        frags = {
                            'key' : 56
                            }, )
                    },
        )
        """

    def testAccountAchievementsOk(self):
        """Test AccountAchievementsOk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
