# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_globalmap_clanbattles200_response_one_of_data_inner import GetGlobalmapClanbattles200ResponseOneOfDataInner

class TestGetGlobalmapClanbattles200ResponseOneOfDataInner(unittest.TestCase):
    """GetGlobalmapClanbattles200ResponseOneOfDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGlobalmapClanbattles200ResponseOneOfDataInner:
        """Test GetGlobalmapClanbattles200ResponseOneOfDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGlobalmapClanbattles200ResponseOneOfDataInner`
        """
        model = GetGlobalmapClanbattles200ResponseOneOfDataInner()
        if include_optional:
            return GetGlobalmapClanbattles200ResponseOneOfDataInner(
                front_id = '',
                front_name = '',
                province_id = '',
                province_name = '',
                time = 56,
                type = '',
                competitor_id = 56,
                attack_type = '',
                vehicle_level = 56
            )
        else:
            return GetGlobalmapClanbattles200ResponseOneOfDataInner(
                front_id = '',
                front_name = '',
                province_id = '',
                province_name = '',
                time = 56,
                type = '',
                competitor_id = 56,
                attack_type = '',
                vehicle_level = 56,
        )
        """

    def testGetGlobalmapClanbattles200ResponseOneOfDataInner(self):
        """Test GetGlobalmapClanbattles200ResponseOneOfDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
