# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_encyclopedia_achievements200_response_one_of_data_value_options_inner_nation_images import GetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages

class TestGetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages(unittest.TestCase):
    """GetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages:
        """Test GetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages`
        """
        model = GetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages()
        if include_optional:
            return GetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages(
                x71 = {
                    'key' : ''
                    },
                x85 = {
                    'key' : ''
                    },
                x180 = {
                    'key' : ''
                    }
            )
        else:
            return GetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages(
                x71 = {
                    'key' : ''
                    },
                x85 = {
                    'key' : ''
                    },
                x180 = {
                    'key' : ''
                    },
        )
        """

    def testGetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages(self):
        """Test GetEncyclopediaAchievements200ResponseOneOfDataValueOptionsInnerNationImages"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
