# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_encyclopedia_badges200_response_one_of_data_value import GetEncyclopediaBadges200ResponseOneOfDataValue

class TestGetEncyclopediaBadges200ResponseOneOfDataValue(unittest.TestCase):
    """GetEncyclopediaBadges200ResponseOneOfDataValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEncyclopediaBadges200ResponseOneOfDataValue:
        """Test GetEncyclopediaBadges200ResponseOneOfDataValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEncyclopediaBadges200ResponseOneOfDataValue`
        """
        model = GetEncyclopediaBadges200ResponseOneOfDataValue()
        if include_optional:
            return GetEncyclopediaBadges200ResponseOneOfDataValue(
                badge_id = 56,
                name = '',
                description = '',
                images = wot_api_client.models.get_encyclopedia_badges_200_response_one_of_data_value_images.get_encyclopedia_badges_200_response_oneOf_data_value_images(
                    big_icon = '', 
                    medium_icon = '', 
                    small_icon = '', )
            )
        else:
            return GetEncyclopediaBadges200ResponseOneOfDataValue(
                badge_id = 56,
                name = '',
                description = '',
                images = wot_api_client.models.get_encyclopedia_badges_200_response_one_of_data_value_images.get_encyclopedia_badges_200_response_oneOf_data_value_images(
                    big_icon = '', 
                    medium_icon = '', 
                    small_icon = '', ),
        )
        """

    def testGetEncyclopediaBadges200ResponseOneOfDataValue(self):
        """Test GetEncyclopediaBadges200ResponseOneOfDataValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
