# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_globalmap_claninfo200_response_one_of_data_value_statistics import GetGlobalmapClaninfo200ResponseOneOfDataValueStatistics

class TestGetGlobalmapClaninfo200ResponseOneOfDataValueStatistics(unittest.TestCase):
    """GetGlobalmapClaninfo200ResponseOneOfDataValueStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGlobalmapClaninfo200ResponseOneOfDataValueStatistics:
        """Test GetGlobalmapClaninfo200ResponseOneOfDataValueStatistics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGlobalmapClaninfo200ResponseOneOfDataValueStatistics`
        """
        model = GetGlobalmapClaninfo200ResponseOneOfDataValueStatistics()
        if include_optional:
            return GetGlobalmapClaninfo200ResponseOneOfDataValueStatistics(
                battles = 56,
                wins = 56,
                losses = 56,
                battles_10_level = 56,
                battles_8_level = 56,
                battles_6_level = 56,
                wins_10_level = 56,
                wins_8_level = 56,
                wins_6_level = 56,
                captures = 56,
                provinces_count = 56
            )
        else:
            return GetGlobalmapClaninfo200ResponseOneOfDataValueStatistics(
                battles = 56,
                wins = 56,
                losses = 56,
                battles_10_level = 56,
                battles_8_level = 56,
                battles_6_level = 56,
                wins_10_level = 56,
                wins_8_level = 56,
                wins_6_level = 56,
                captures = 56,
                provinces_count = 56,
        )
        """

    def testGetGlobalmapClaninfo200ResponseOneOfDataValueStatistics(self):
        """Test GetGlobalmapClaninfo200ResponseOneOfDataValueStatistics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
