# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.api.global_map_api import GlobalMapApi


class TestGlobalMapApi(unittest.TestCase):
    """GlobalMapApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GlobalMapApi()

    def tearDown(self) -> None:
        pass

    def test_get_globalmap_clanbattles(self) -> None:
        """Test case for get_globalmap_clanbattles

        Clan's battles
        """
        pass

    def test_get_globalmap_claninfo(self) -> None:
        """Test case for get_globalmap_claninfo

        Clan details
        """
        pass

    def test_get_globalmap_clanprovinces(self) -> None:
        """Test case for get_globalmap_clanprovinces

        Clan's provinces
        """
        pass

    def test_get_globalmap_eventaccountinfo(self) -> None:
        """Test case for get_globalmap_eventaccountinfo

        Account event information
        """
        pass

    def test_get_globalmap_eventaccountratingneighbors(self) -> None:
        """Test case for get_globalmap_eventaccountratingneighbors

        Adjacent positions in event account rating
        """
        pass

    def test_get_globalmap_eventaccountratings(self) -> None:
        """Test case for get_globalmap_eventaccountratings

        Event account rating
        """
        pass

    def test_get_globalmap_eventclaninfo(self) -> None:
        """Test case for get_globalmap_eventclaninfo

        Clan event information
        """
        pass

    def test_get_globalmap_eventclantasks(self) -> None:
        """Test case for get_globalmap_eventclantasks

        Clan event missions
        """
        pass

    def test_get_globalmap_eventrating(self) -> None:
        """Test case for get_globalmap_eventrating

        Event clan ratings
        """
        pass

    def test_get_globalmap_eventratingneighbors(self) -> None:
        """Test case for get_globalmap_eventratingneighbors

        Adjacent position in event clan rating
        """
        pass

    def test_get_globalmap_events(self) -> None:
        """Test case for get_globalmap_events

        Events
        """
        pass

    def test_get_globalmap_fronts(self) -> None:
        """Test case for get_globalmap_fronts

        Fronts
        """
        pass

    def test_get_globalmap_info(self) -> None:
        """Test case for get_globalmap_info

        Map status
        """
        pass

    def test_get_globalmap_provinces(self) -> None:
        """Test case for get_globalmap_provinces

        Provinces
        """
        pass

    def test_get_globalmap_seasonaccountinfo(self) -> None:
        """Test case for get_globalmap_seasonaccountinfo

        Account's season data
        """
        pass

    def test_get_globalmap_seasonrating(self) -> None:
        """Test case for get_globalmap_seasonrating

        Season rating
        """
        pass

    def test_get_globalmap_seasonratingneighbors(self) -> None:
        """Test case for get_globalmap_seasonratingneighbors

        Adjacent positions in season clan rating
        """
        pass

    def test_get_globalmap_seasons(self) -> None:
        """Test case for get_globalmap_seasons

        Seasons
        """
        pass


if __name__ == '__main__':
    unittest.main()
