# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_clanratings_types200_response_one_of_data_value import GetClanratingsTypes200ResponseOneOfDataValue

class TestGetClanratingsTypes200ResponseOneOfDataValue(unittest.TestCase):
    """GetClanratingsTypes200ResponseOneOfDataValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClanratingsTypes200ResponseOneOfDataValue:
        """Test GetClanratingsTypes200ResponseOneOfDataValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClanratingsTypes200ResponseOneOfDataValue`
        """
        model = GetClanratingsTypes200ResponseOneOfDataValue()
        if include_optional:
            return GetClanratingsTypes200ResponseOneOfDataValue(
                type = '',
                rank_fields = [
                    ''
                    ]
            )
        else:
            return GetClanratingsTypes200ResponseOneOfDataValue(
                type = '',
                rank_fields = [
                    ''
                    ],
        )
        """

    def testGetClanratingsTypes200ResponseOneOfDataValue(self):
        """Test GetClanratingsTypes200ResponseOneOfDataValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
