# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_encyclopedia_personalmissions200_response import GetEncyclopediaPersonalmissions200Response

class TestGetEncyclopediaPersonalmissions200Response(unittest.TestCase):
    """GetEncyclopediaPersonalmissions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEncyclopediaPersonalmissions200Response:
        """Test GetEncyclopediaPersonalmissions200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEncyclopediaPersonalmissions200Response`
        """
        model = GetEncyclopediaPersonalmissions200Response()
        if include_optional:
            return GetEncyclopediaPersonalmissions200Response(
                status = 'error',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value.get_encyclopedia_personalmissions_200_response_oneOf_data_value(
                        campaign_id = 56, 
                        name = '', 
                        description = '', 
                        operations = {
                            'key' : wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value_operations_value.get_encyclopedia_personalmissions_200_response_oneOf_data_value_operations_value(
                                operation_id = 56, 
                                name = '', 
                                description = '', 
                                image = '', 
                                sets_count = 56, 
                                missions_in_set = 56, 
                                next_id = 56, 
                                sets_to_next = 56, 
                                reward = wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value_operations_value_reward.get_encyclopedia_personalmissions_200_response_oneOf_data_value_operations_value_reward(
                                    slots = 56, 
                                    tanks = [
                                        56
                                        ], ), 
                                missions = {
                                    'key' : wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value_operations_value_missions_value.get_encyclopedia_personalmissions_200_response_oneOf_data_value_operations_value_missions_value(
                                        mission_id = 56, 
                                        set_id = 56, 
                                        name = '', 
                                        description = '', 
                                        hint = '', 
                                        min_level = 56, 
                                        max_level = 56, 
                                        tags = [
                                            ''
                                            ], 
                                        rewards = {
                                            'key' : wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value_operations_value_missions_value_rewards_value.get_encyclopedia_personalmissions_200_response_oneOf_data_value_operations_value_missions_value_rewards_value(
                                                conditions = '', 
                                                credits = 56, 
                                                items = {
                                                    'key' : 56
                                                    }, 
                                                premium = 56, 
                                                free_xp = 56, 
                                                tokens = 56, 
                                                slots = 56, 
                                                berths = 56, )
                                            }, )
                                    }, )
                            }, )
                    },
                error = wot_api_client.models.get_account_list_200_response_one_of_1_error.get_account_list_200_response_oneOf_1_error(
                    code = 1.337, 
                    message = '', 
                    field = '', 
                    value = '', )
            )
        else:
            return GetEncyclopediaPersonalmissions200Response(
                status = 'error',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value.get_encyclopedia_personalmissions_200_response_oneOf_data_value(
                        campaign_id = 56, 
                        name = '', 
                        description = '', 
                        operations = {
                            'key' : wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value_operations_value.get_encyclopedia_personalmissions_200_response_oneOf_data_value_operations_value(
                                operation_id = 56, 
                                name = '', 
                                description = '', 
                                image = '', 
                                sets_count = 56, 
                                missions_in_set = 56, 
                                next_id = 56, 
                                sets_to_next = 56, 
                                reward = wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value_operations_value_reward.get_encyclopedia_personalmissions_200_response_oneOf_data_value_operations_value_reward(
                                    slots = 56, 
                                    tanks = [
                                        56
                                        ], ), 
                                missions = {
                                    'key' : wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value_operations_value_missions_value.get_encyclopedia_personalmissions_200_response_oneOf_data_value_operations_value_missions_value(
                                        mission_id = 56, 
                                        set_id = 56, 
                                        name = '', 
                                        description = '', 
                                        hint = '', 
                                        min_level = 56, 
                                        max_level = 56, 
                                        tags = [
                                            ''
                                            ], 
                                        rewards = {
                                            'key' : wot_api_client.models.get_encyclopedia_personalmissions_200_response_one_of_data_value_operations_value_missions_value_rewards_value.get_encyclopedia_personalmissions_200_response_oneOf_data_value_operations_value_missions_value_rewards_value(
                                                conditions = '', 
                                                credits = 56, 
                                                items = {
                                                    'key' : 56
                                                    }, 
                                                premium = 56, 
                                                free_xp = 56, 
                                                tokens = 56, 
                                                slots = 56, 
                                                berths = 56, )
                                            }, )
                                    }, )
                            }, )
                    },
                error = wot_api_client.models.get_account_list_200_response_one_of_1_error.get_account_list_200_response_oneOf_1_error(
                    code = 1.337, 
                    message = '', 
                    field = '', 
                    value = '', ),
        )
        """

    def testGetEncyclopediaPersonalmissions200Response(self):
        """Test GetEncyclopediaPersonalmissions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
