# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_encyclopedia_vehicles200_response_one_of_data_value_images import GetEncyclopediaVehicles200ResponseOneOfDataValueImages

class TestGetEncyclopediaVehicles200ResponseOneOfDataValueImages(unittest.TestCase):
    """GetEncyclopediaVehicles200ResponseOneOfDataValueImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEncyclopediaVehicles200ResponseOneOfDataValueImages:
        """Test GetEncyclopediaVehicles200ResponseOneOfDataValueImages
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEncyclopediaVehicles200ResponseOneOfDataValueImages`
        """
        model = GetEncyclopediaVehicles200ResponseOneOfDataValueImages()
        if include_optional:
            return GetEncyclopediaVehicles200ResponseOneOfDataValueImages(
                big_icon = '',
                small_icon = '',
                contour_icon = ''
            )
        else:
            return GetEncyclopediaVehicles200ResponseOneOfDataValueImages(
                big_icon = '',
                small_icon = '',
                contour_icon = '',
        )
        """

    def testGetEncyclopediaVehicles200ResponseOneOfDataValueImages(self):
        """Test GetEncyclopediaVehicles200ResponseOneOfDataValueImages"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
