# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_encyclopedia_boosters200_response import GetEncyclopediaBoosters200Response

class TestGetEncyclopediaBoosters200Response(unittest.TestCase):
    """GetEncyclopediaBoosters200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEncyclopediaBoosters200Response:
        """Test GetEncyclopediaBoosters200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEncyclopediaBoosters200Response`
        """
        model = GetEncyclopediaBoosters200Response()
        if include_optional:
            return GetEncyclopediaBoosters200Response(
                status = 'error',
                meta = wot_api_client.models.encyclopedia_boosters_meta.encyclopedia_boosters_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.encyclopedia_boosters_data_value.encyclopedia_boosters_data_value(
                        booster_id = 56, 
                        name = '', 
                        description = '', 
                        images = wot_api_client.models.encyclopedia_boosters_data_value_images.encyclopedia_boosters_data_value_images(
                            large = '', 
                            small = '', ), 
                        lifetime = 56, 
                        resource = '', 
                        is_auto = True, 
                        expires_at = 56, 
                        price_credit = 56, 
                        price_gold = 56, )
                    },
                error = wot_api_client.models.error.error()
            )
        else:
            return GetEncyclopediaBoosters200Response(
                status = 'error',
                meta = wot_api_client.models.encyclopedia_boosters_meta.encyclopedia_boosters_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.encyclopedia_boosters_data_value.encyclopedia_boosters_data_value(
                        booster_id = 56, 
                        name = '', 
                        description = '', 
                        images = wot_api_client.models.encyclopedia_boosters_data_value_images.encyclopedia_boosters_data_value_images(
                            large = '', 
                            small = '', ), 
                        lifetime = 56, 
                        resource = '', 
                        is_auto = True, 
                        expires_at = 56, 
                        price_credit = 56, 
                        price_gold = 56, )
                    },
                error = wot_api_client.models.error.error(),
        )
        """

    def testGetEncyclopediaBoosters200Response(self):
        """Test GetEncyclopediaBoosters200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
