# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.account_tanks_ok import AccountTanksOk

class TestAccountTanksOk(unittest.TestCase):
    """AccountTanksOk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountTanksOk:
        """Test AccountTanksOk
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountTanksOk`
        """
        model = AccountTanksOk()
        if include_optional:
            return AccountTanksOk(
                status = 'ok',
                meta = wot_api_client.models.account_tanks_meta.account_tanks_meta(
                    count = 56, ),
                data = {
                    'key' : [
                        wot_api_client.models.account_tanks_data_value_inner.account_tanks_data_value_inner(
                            tank_id = 56, 
                            mark_of_mastery = 56, 
                            statistics = wot_api_client.models.account_tanks_data_value_inner_statistics.account_tanks_data_value_inner_statistics(
                                battles = 56, 
                                wins = 56, ), )
                        ]
                    }
            )
        else:
            return AccountTanksOk(
                status = 'ok',
                meta = wot_api_client.models.account_tanks_meta.account_tanks_meta(
                    count = 56, ),
                data = {
                    'key' : [
                        wot_api_client.models.account_tanks_data_value_inner.account_tanks_data_value_inner(
                            tank_id = 56, 
                            mark_of_mastery = 56, 
                            statistics = wot_api_client.models.account_tanks_data_value_inner_statistics.account_tanks_data_value_inner_statistics(
                                battles = 56, 
                                wins = 56, ), )
                        ]
                    },
        )
        """

    def testAccountTanksOk(self):
        """Test AccountTanksOk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
