# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_auth_login200_response import GetAuthLogin200Response

class TestGetAuthLogin200Response(unittest.TestCase):
    """GetAuthLogin200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAuthLogin200Response:
        """Test GetAuthLogin200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAuthLogin200Response`
        """
        model = GetAuthLogin200Response()
        if include_optional:
            return GetAuthLogin200Response(
                status = 'error',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = wot_api_client.models.get_auth_login_200_response_one_of_data.get_auth_login_200_response_oneOf_data(
                    location = '', ),
                error = wot_api_client.models.get_account_list_200_response_one_of_1_error.get_account_list_200_response_oneOf_1_error(
                    code = 1.337, 
                    message = '', 
                    field = '', 
                    value = '', )
            )
        else:
            return GetAuthLogin200Response(
                status = 'error',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = wot_api_client.models.get_auth_login_200_response_one_of_data.get_auth_login_200_response_oneOf_data(
                    location = '', ),
                error = wot_api_client.models.get_account_list_200_response_one_of_1_error.get_account_list_200_response_oneOf_1_error(
                    code = 1.337, 
                    message = '', 
                    field = '', 
                    value = '', ),
        )
        """

    def testGetAuthLogin200Response(self):
        """Test GetAuthLogin200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
