# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_account_info200_response_one_of_data_value_private_boosters_value import GetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue

class TestGetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue(unittest.TestCase):
    """GetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue:
        """Test GetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue`
        """
        model = GetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue()
        if include_optional:
            return GetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue(
                state = '',
                count = 56,
                expiration_time = 56
            )
        else:
            return GetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue(
                state = '',
                count = 56,
                expiration_time = 56,
        )
        """

    def testGetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue(self):
        """Test GetAccountInfo200ResponseOneOfDataValuePrivateBoostersValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
