# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_globalmap_eventaccountinfo200_response import GetGlobalmapEventaccountinfo200Response

class TestGetGlobalmapEventaccountinfo200Response(unittest.TestCase):
    """GetGlobalmapEventaccountinfo200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGlobalmapEventaccountinfo200Response:
        """Test GetGlobalmapEventaccountinfo200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGlobalmapEventaccountinfo200Response`
        """
        model = GetGlobalmapEventaccountinfo200Response()
        if include_optional:
            return GetGlobalmapEventaccountinfo200Response(
                status = 'error',
                meta = wot_api_client.models.globalmap_eventaccountinfo_meta.globalmap_eventaccountinfo_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.globalmap_eventaccountinfo_data_value.globalmap_eventaccountinfo_data_value(
                        events = {
                            'key' : [
                                wot_api_client.models.globalmap_eventaccountinfo_data_value_events_value_inner.globalmap_eventaccountinfo_data_value_events_value_inner(
                                    account_id = 56, 
                                    award_level = '', 
                                    battles = 56, 
                                    battles_to_award = 56, 
                                    clan_id = 56, 
                                    clan_rank = 56, 
                                    event_id = '', 
                                    fame_points = 56, 
                                    fame_points_since_turn = 56, 
                                    fame_points_to_improve_award = 56, 
                                    front_id = '', 
                                    rank = 56, 
                                    rank_delta = 56, 
                                    updated_at = 56, 
                                    url = '', )
                                ]
                            }, )
                    },
                error = None
            )
        else:
            return GetGlobalmapEventaccountinfo200Response(
                status = 'error',
                meta = wot_api_client.models.globalmap_eventaccountinfo_meta.globalmap_eventaccountinfo_meta(
                    count = 56, ),
                data = {
                    'key' : wot_api_client.models.globalmap_eventaccountinfo_data_value.globalmap_eventaccountinfo_data_value(
                        events = {
                            'key' : [
                                wot_api_client.models.globalmap_eventaccountinfo_data_value_events_value_inner.globalmap_eventaccountinfo_data_value_events_value_inner(
                                    account_id = 56, 
                                    award_level = '', 
                                    battles = 56, 
                                    battles_to_award = 56, 
                                    clan_id = 56, 
                                    clan_rank = 56, 
                                    event_id = '', 
                                    fame_points = 56, 
                                    fame_points_since_turn = 56, 
                                    fame_points_to_improve_award = 56, 
                                    front_id = '', 
                                    rank = 56, 
                                    rank_delta = 56, 
                                    updated_at = 56, 
                                    url = '', )
                                ]
                            }, )
                    },
                error = None,
        )
        """

    def testGetGlobalmapEventaccountinfo200Response(self):
        """Test GetGlobalmapEventaccountinfo200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
