# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.stronghold_claninfo_data_value_skirmish_statistics import StrongholdClaninfoDataValueSkirmishStatistics

class TestStrongholdClaninfoDataValueSkirmishStatistics(unittest.TestCase):
    """StrongholdClaninfoDataValueSkirmishStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StrongholdClaninfoDataValueSkirmishStatistics:
        """Test StrongholdClaninfoDataValueSkirmishStatistics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StrongholdClaninfoDataValueSkirmishStatistics`
        """
        model = StrongholdClaninfoDataValueSkirmishStatistics()
        if include_optional:
            return StrongholdClaninfoDataValueSkirmishStatistics(
                total_10 = 56,
                win_10 = 56,
                lose_10 = 56,
                total_8 = 56,
                win_8 = 56,
                lose_8 = 56,
                total_6 = 56,
                win_6 = 56,
                lose_6 = 56,
                total_10_in_28d = 56,
                win_10_in_28d = 56,
                total_8_in_28d = 56,
                win_8_in_28d = 56,
                total_6_in_28d = 56,
                win_6_in_28d = 56,
                last_time_10 = 56,
                last_time_8 = 56,
                last_time_6 = 56
            )
        else:
            return StrongholdClaninfoDataValueSkirmishStatistics(
                total_10 = 56,
                win_10 = 56,
                lose_10 = 56,
                total_8 = 56,
                win_8 = 56,
                lose_8 = 56,
                total_6 = 56,
                win_6 = 56,
                lose_6 = 56,
                total_10_in_28d = 56,
                win_10_in_28d = 56,
                total_8_in_28d = 56,
                win_8_in_28d = 56,
                total_6_in_28d = 56,
                win_6_in_28d = 56,
                last_time_10 = 56,
                last_time_8 = 56,
                last_time_6 = 56,
        )
        """

    def testStrongholdClaninfoDataValueSkirmishStatistics(self):
        """Test StrongholdClaninfoDataValueSkirmishStatistics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
