# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.globalmap_eventratingneighbors_data_inner import GlobalmapEventratingneighborsDataInner

class TestGlobalmapEventratingneighborsDataInner(unittest.TestCase):
    """GlobalmapEventratingneighborsDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalmapEventratingneighborsDataInner:
        """Test GlobalmapEventratingneighborsDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalmapEventratingneighborsDataInner`
        """
        model = GlobalmapEventratingneighborsDataInner()
        if include_optional:
            return GlobalmapEventratingneighborsDataInner(
                clan_id = 56,
                name = '',
                tag = '',
                color = '',
                award_level = '',
                rank = 56,
                rank_delta = 56,
                updated_at = 56,
                battle_fame_points = 56,
                total_fame_points = 56,
                task_fame_points = 56,
                fame_points_to_improve_award = 56
            )
        else:
            return GlobalmapEventratingneighborsDataInner(
                clan_id = 56,
                name = '',
                tag = '',
                color = '',
                award_level = '',
                rank = 56,
                rank_delta = 56,
                updated_at = 56,
                battle_fame_points = 56,
                total_fame_points = 56,
                task_fame_points = 56,
                fame_points_to_improve_award = 56,
        )
        """

    def testGlobalmapEventratingneighborsDataInner(self):
        """Test GlobalmapEventratingneighborsDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
