# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.encyclopedia_personalmissions_data_value_operations_value_missions_value_rewards_value import EncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue

class TestEncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue(unittest.TestCase):
    """EncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue:
        """Test EncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue`
        """
        model = EncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue()
        if include_optional:
            return EncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue(
                conditions = '',
                credits = 56,
                items = {
                    'key' : 56
                    },
                premium = 56,
                free_xp = 56,
                tokens = 56,
                slots = 56,
                berths = 56
            )
        else:
            return EncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue(
                conditions = '',
                credits = 56,
                items = {
                    'key' : 56
                    },
                premium = 56,
                free_xp = 56,
                tokens = 56,
                slots = 56,
                berths = 56,
        )
        """

    def testEncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue(self):
        """Test EncyclopediaPersonalmissionsDataValueOperationsValueMissionsValueRewardsValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
