# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.encyclopedia_vehicles_data_value_modules_tree_value import EncyclopediaVehiclesDataValueModulesTreeValue

class TestEncyclopediaVehiclesDataValueModulesTreeValue(unittest.TestCase):
    """EncyclopediaVehiclesDataValueModulesTreeValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EncyclopediaVehiclesDataValueModulesTreeValue:
        """Test EncyclopediaVehiclesDataValueModulesTreeValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EncyclopediaVehiclesDataValueModulesTreeValue`
        """
        model = EncyclopediaVehiclesDataValueModulesTreeValue()
        if include_optional:
            return EncyclopediaVehiclesDataValueModulesTreeValue(
                module_id = 56,
                name = '',
                type = '',
                price_credit = 56,
                price_xp = 56,
                next_tanks = [
                    56
                    ],
                next_modules = [
                    56
                    ],
                is_default = True
            )
        else:
            return EncyclopediaVehiclesDataValueModulesTreeValue(
                module_id = 56,
                name = '',
                type = '',
                price_credit = 56,
                price_xp = 56,
                next_tanks = [
                    56
                    ],
                next_modules = [
                    56
                    ],
                is_default = True,
        )
        """

    def testEncyclopediaVehiclesDataValueModulesTreeValue(self):
        """Test EncyclopediaVehiclesDataValueModulesTreeValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
