# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_clans_glossary200_response_one_of import GetClansGlossary200ResponseOneOf

class TestGetClansGlossary200ResponseOneOf(unittest.TestCase):
    """GetClansGlossary200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClansGlossary200ResponseOneOf:
        """Test GetClansGlossary200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClansGlossary200ResponseOneOf`
        """
        model = GetClansGlossary200ResponseOneOf()
        if include_optional:
            return GetClansGlossary200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.meta.meta(),
                data = wot_api_client.models.get_clans_glossary_200_response_one_of_data.get_clans_glossary_200_response_oneOf_data(
                    clans_roles = {
                        'key' : ''
                        }, )
            )
        else:
            return GetClansGlossary200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.meta.meta(),
                data = wot_api_client.models.get_clans_glossary_200_response_one_of_data.get_clans_glossary_200_response_oneOf_data(
                    clans_roles = {
                        'key' : ''
                        }, ),
        )
        """

    def testGetClansGlossary200ResponseOneOf(self):
        """Test GetClansGlossary200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
