# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_clans_list200_response_one_of import GetClansList200ResponseOneOf

class TestGetClansList200ResponseOneOf(unittest.TestCase):
    """GetClansList200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClansList200ResponseOneOf:
        """Test GetClansList200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClansList200ResponseOneOf`
        """
        model = GetClansList200ResponseOneOf()
        if include_optional:
            return GetClansList200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_clans_list_200_response_one_of_meta.get_clans_list_200_response_oneOf_meta(
                    count = 56, 
                    total = 56, ),
                data = [
                    wot_api_client.models.get_clans_list_200_response_one_of_data_inner.get_clans_list_200_response_oneOf_data_inner(
                        clan_id = 56, 
                        name = '', 
                        tag = '', 
                        created_at = 56, 
                        color = '', 
                        members_count = 56, 
                        emblems = wot_api_client.models.get_clans_list_200_response_one_of_data_inner_emblems.get_clans_list_200_response_oneOf_data_inner_emblems(
                            x24 = {
                                'key' : ''
                                }, 
                            x32 = {
                                'key' : ''
                                }, 
                            x64 = {
                                'key' : ''
                                }, 
                            x195 = {
                                'key' : ''
                                }, 
                            x256 = {
                                'key' : ''
                                }, ), )
                    ]
            )
        else:
            return GetClansList200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_clans_list_200_response_one_of_meta.get_clans_list_200_response_oneOf_meta(
                    count = 56, 
                    total = 56, ),
                data = [
                    wot_api_client.models.get_clans_list_200_response_one_of_data_inner.get_clans_list_200_response_oneOf_data_inner(
                        clan_id = 56, 
                        name = '', 
                        tag = '', 
                        created_at = 56, 
                        color = '', 
                        members_count = 56, 
                        emblems = wot_api_client.models.get_clans_list_200_response_one_of_data_inner_emblems.get_clans_list_200_response_oneOf_data_inner_emblems(
                            x24 = {
                                'key' : ''
                                }, 
                            x32 = {
                                'key' : ''
                                }, 
                            x64 = {
                                'key' : ''
                                }, 
                            x195 = {
                                'key' : ''
                                }, 
                            x256 = {
                                'key' : ''
                                }, ), )
                    ],
        )
        """

    def testGetClansList200ResponseOneOf(self):
        """Test GetClansList200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
