# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.prolongate200_response_one_of import Prolongate200ResponseOneOf

class TestProlongate200ResponseOneOf(unittest.TestCase):
    """Prolongate200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Prolongate200ResponseOneOf:
        """Test Prolongate200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Prolongate200ResponseOneOf`
        """
        model = Prolongate200ResponseOneOf()
        if include_optional:
            return Prolongate200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = wot_api_client.models.prolongate_200_response_one_of_data.prolongate_200_response_oneOf_data(
                    access_token = '', 
                    expires_at = 56, 
                    account_id = 56, )
            )
        else:
            return Prolongate200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = wot_api_client.models.prolongate_200_response_one_of_data.prolongate_200_response_oneOf_data(
                    access_token = '', 
                    expires_at = 56, 
                    account_id = 56, ),
        )
        """

    def testProlongate200ResponseOneOf(self):
        """Test Prolongate200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
