# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.globalmap_claninfo_data_value import GlobalmapClaninfoDataValue

class TestGlobalmapClaninfoDataValue(unittest.TestCase):
    """GlobalmapClaninfoDataValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalmapClaninfoDataValue:
        """Test GlobalmapClaninfoDataValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalmapClaninfoDataValue`
        """
        model = GlobalmapClaninfoDataValue()
        if include_optional:
            return GlobalmapClaninfoDataValue(
                clan_id = 56,
                tag = '',
                name = '',
                statistics = wot_api_client.models.globalmap_claninfo_data_value_statistics.globalmap_claninfo_data_value_statistics(
                    battles = 56, 
                    wins = 56, 
                    losses = 56, 
                    battles_10_level = 56, 
                    battles_8_level = 56, 
                    battles_6_level = 56, 
                    wins_10_level = 56, 
                    wins_8_level = 56, 
                    wins_6_level = 56, 
                    captures = 56, 
                    provinces_count = 56, ),
                ratings = wot_api_client.models.globalmap_claninfo_data_value_ratings.globalmap_claninfo_data_value_ratings(
                    updated_at = 56, 
                    elo_6 = 56, 
                    elo_8 = 56, 
                    elo_10 = 56, ),
                private = wot_api_client.models.globalmap_claninfo_data_value_private.globalmap_claninfo_data_value_private(
                    daily_wage = 56, 
                    influence = 56, )
            )
        else:
            return GlobalmapClaninfoDataValue(
                clan_id = 56,
                tag = '',
                name = '',
                statistics = wot_api_client.models.globalmap_claninfo_data_value_statistics.globalmap_claninfo_data_value_statistics(
                    battles = 56, 
                    wins = 56, 
                    losses = 56, 
                    battles_10_level = 56, 
                    battles_8_level = 56, 
                    battles_6_level = 56, 
                    wins_10_level = 56, 
                    wins_8_level = 56, 
                    wins_6_level = 56, 
                    captures = 56, 
                    provinces_count = 56, ),
                ratings = wot_api_client.models.globalmap_claninfo_data_value_ratings.globalmap_claninfo_data_value_ratings(
                    updated_at = 56, 
                    elo_6 = 56, 
                    elo_8 = 56, 
                    elo_10 = 56, ),
                private = wot_api_client.models.globalmap_claninfo_data_value_private.globalmap_claninfo_data_value_private(
                    daily_wage = 56, 
                    influence = 56, ),
        )
        """

    def testGlobalmapClaninfoDataValue(self):
        """Test GlobalmapClaninfoDataValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
