# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_clans_memberhistory200_response import GetClansMemberhistory200Response

class TestGetClansMemberhistory200Response(unittest.TestCase):
    """GetClansMemberhistory200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClansMemberhistory200Response:
        """Test GetClansMemberhistory200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClansMemberhistory200Response`
        """
        model = GetClansMemberhistory200Response()
        if include_optional:
            return GetClansMemberhistory200Response(
                status = 'error',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = {
                    'key' : [
                        wot_api_client.models.get_clans_memberhistory_200_response_one_of_data_value_inner.get_clans_memberhistory_200_response_oneOf_data_value_inner(
                            account_id = 56, 
                            clan_id = 56, 
                            joined_at = 56, 
                            left_at = 56, 
                            role = '', )
                        ]
                    },
                error = wot_api_client.models.get_account_list_200_response_one_of_1_error.get_account_list_200_response_oneOf_1_error(
                    code = 1.337, 
                    message = '', 
                    field = '', 
                    value = '', )
            )
        else:
            return GetClansMemberhistory200Response(
                status = 'error',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = {
                    'key' : [
                        wot_api_client.models.get_clans_memberhistory_200_response_one_of_data_value_inner.get_clans_memberhistory_200_response_oneOf_data_value_inner(
                            account_id = 56, 
                            clan_id = 56, 
                            joined_at = 56, 
                            left_at = 56, 
                            role = '', )
                        ]
                    },
                error = wot_api_client.models.get_account_list_200_response_one_of_1_error.get_account_list_200_response_oneOf_1_error(
                    code = 1.337, 
                    message = '', 
                    field = '', 
                    value = '', ),
        )
        """

    def testGetClansMemberhistory200Response(self):
        """Test GetClansMemberhistory200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
