# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_tanks_mastery200_response import GetTanksMastery200Response

class TestGetTanksMastery200Response(unittest.TestCase):
    """GetTanksMastery200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTanksMastery200Response:
        """Test GetTanksMastery200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTanksMastery200Response`
        """
        model = GetTanksMastery200Response()
        if include_optional:
            return GetTanksMastery200Response(
                status = 'error',
                meta = wot_api_client.models.tanks_mastery_meta.tanks_mastery_meta(
                    count = 56, ),
                data = wot_api_client.models.tanks_mastery_data.tanks_mastery_data(
                    distribution = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    updated_at = 56, ),
                error = wot_api_client.models.error.error()
            )
        else:
            return GetTanksMastery200Response(
                status = 'error',
                meta = wot_api_client.models.tanks_mastery_meta.tanks_mastery_meta(
                    count = 56, ),
                data = wot_api_client.models.tanks_mastery_data.tanks_mastery_data(
                    distribution = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    updated_at = 56, ),
                error = wot_api_client.models.error.error(),
        )
        """

    def testGetTanksMastery200Response(self):
        """Test GetTanksMastery200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
