# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_encyclopedia_vehicles200_response_one_of_data_value_default_profile_turret import GetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret

class TestGetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret(unittest.TestCase):
    """GetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret:
        """Test GetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret`
        """
        model = GetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret()
        if include_optional:
            return GetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret(
                tier = 56,
                name = '',
                weight = 56,
                tag = '',
                view_range = 56,
                traverse_speed = 56,
                hp = 56,
                traverse_left_arc = 56,
                traverse_right_arc = 56
            )
        else:
            return GetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret(
                tier = 56,
                name = '',
                weight = 56,
                tag = '',
                view_range = 56,
                traverse_speed = 56,
                hp = 56,
                traverse_left_arc = 56,
                traverse_right_arc = 56,
        )
        """

    def testGetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret(self):
        """Test GetEncyclopediaVehicles200ResponseOneOfDataValueDefaultProfileTurret"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
