# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_tanks_achievements200_response import GetTanksAchievements200Response

class TestGetTanksAchievements200Response(unittest.TestCase):
    """GetTanksAchievements200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTanksAchievements200Response:
        """Test GetTanksAchievements200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTanksAchievements200Response`
        """
        model = GetTanksAchievements200Response()
        if include_optional:
            return GetTanksAchievements200Response(
                status = 'error',
                meta = wot_api_client.models.tanks_achievements_meta.tanks_achievements_meta(
                    count = 56, ),
                data = {
                    'key' : [
                        wot_api_client.models.tanks_achievements_data_value_inner.tanks_achievements_data_value_inner(
                            account_id = 56, 
                            tank_id = 56, 
                            achievements = {
                                'key' : 56
                                }, 
                            series = {
                                'key' : 56
                                }, 
                            max_series = {
                                'key' : 56
                                }, )
                        ]
                    },
                error = wot_api_client.models.error.error()
            )
        else:
            return GetTanksAchievements200Response(
                status = 'error',
                meta = wot_api_client.models.tanks_achievements_meta.tanks_achievements_meta(
                    count = 56, ),
                data = {
                    'key' : [
                        wot_api_client.models.tanks_achievements_data_value_inner.tanks_achievements_data_value_inner(
                            account_id = 56, 
                            tank_id = 56, 
                            achievements = {
                                'key' : 56
                                }, 
                            series = {
                                'key' : 56
                                }, 
                            max_series = {
                                'key' : 56
                                }, )
                        ]
                    },
                error = wot_api_client.models.error.error(),
        )
        """

    def testGetTanksAchievements200Response(self):
        """Test GetTanksAchievements200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
