# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_tanks_mastery200_response_one_of import GetTanksMastery200ResponseOneOf

class TestGetTanksMastery200ResponseOneOf(unittest.TestCase):
    """GetTanksMastery200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTanksMastery200ResponseOneOf:
        """Test GetTanksMastery200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTanksMastery200ResponseOneOf`
        """
        model = GetTanksMastery200ResponseOneOf()
        if include_optional:
            return GetTanksMastery200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = wot_api_client.models.get_tanks_mastery_200_response_one_of_data.get_tanks_mastery_200_response_oneOf_data(
                    distribution = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    updated_at = 56, )
            )
        else:
            return GetTanksMastery200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = wot_api_client.models.get_tanks_mastery_200_response_one_of_data.get_tanks_mastery_200_response_oneOf_data(
                    distribution = {
                        'key' : {
                            'key' : 56
                            }
                        }, 
                    updated_at = 56, ),
        )
        """

    def testGetTanksMastery200ResponseOneOf(self):
        """Test GetTanksMastery200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
