# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_clanratings_top200_response_one_of import GetClanratingsTop200ResponseOneOf

class TestGetClanratingsTop200ResponseOneOf(unittest.TestCase):
    """GetClanratingsTop200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClanratingsTop200ResponseOneOf:
        """Test GetClanratingsTop200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClanratingsTop200ResponseOneOf`
        """
        model = GetClanratingsTop200ResponseOneOf()
        if include_optional:
            return GetClanratingsTop200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = [
                    wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner.get_clanratings_top_200_response_oneOf_data_inner(
                        clan_id = 56, 
                        clan_name = '', 
                        clan_tag = '', 
                        v10l_avg = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_v10l_avg.get_clanratings_top_200_response_oneOf_data_inner_v10l_avg(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        battles_count_avg = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_battles_count_avg.get_clanratings_top_200_response_oneOf_data_inner_battles_count_avg(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        battles_count_avg_daily = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_battles_count_avg_daily.get_clanratings_top_200_response_oneOf_data_inner_battles_count_avg_daily(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        global_rating_avg = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_global_rating_avg.get_clanratings_top_200_response_oneOf_data_inner_global_rating_avg(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        global_rating_weighted_avg = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_global_rating_weighted_avg.get_clanratings_top_200_response_oneOf_data_inner_global_rating_weighted_avg(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        efficiency = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_efficiency.get_clanratings_top_200_response_oneOf_data_inner_efficiency(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        wins_ratio_avg = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_wins_ratio_avg.get_clanratings_clans_200_response_oneOf_data_value_wins_ratio_avg(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        rating_fort = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_rating_fort.get_clanratings_clans_200_response_oneOf_data_value_rating_fort(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        fb_elo_rating = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_fb_elo_rating.get_clanratings_clans_200_response_oneOf_data_value_fb_elo_rating(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        fb_elo_rating_10 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_fb_elo_rating_10.get_clanratings_clans_200_response_oneOf_data_value_fb_elo_rating_10(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        fb_elo_rating_8 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_fb_elo_rating_8.get_clanratings_clans_200_response_oneOf_data_value_fb_elo_rating_8(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        fb_elo_rating_6 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_fb_elo_rating_6.get_clanratings_clans_200_response_oneOf_data_value_fb_elo_rating_6(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        gm_elo_rating = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_gm_elo_rating.get_clanratings_clans_200_response_oneOf_data_value_gm_elo_rating(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        gm_elo_rating_10 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_gm_elo_rating_10.get_clanratings_clans_200_response_oneOf_data_value_gm_elo_rating_10(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        gm_elo_rating_8 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_gm_elo_rating_8.get_clanratings_clans_200_response_oneOf_data_value_gm_elo_rating_8(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        gm_elo_rating_6 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_gm_elo_rating_6.get_clanratings_clans_200_response_oneOf_data_value_gm_elo_rating_6(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        exclude_reasons = {
                            'key' : ''
                            }, )
                    ]
            )
        else:
            return GetClanratingsTop200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = [
                    wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner.get_clanratings_top_200_response_oneOf_data_inner(
                        clan_id = 56, 
                        clan_name = '', 
                        clan_tag = '', 
                        v10l_avg = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_v10l_avg.get_clanratings_top_200_response_oneOf_data_inner_v10l_avg(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        battles_count_avg = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_battles_count_avg.get_clanratings_top_200_response_oneOf_data_inner_battles_count_avg(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        battles_count_avg_daily = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_battles_count_avg_daily.get_clanratings_top_200_response_oneOf_data_inner_battles_count_avg_daily(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        global_rating_avg = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_global_rating_avg.get_clanratings_top_200_response_oneOf_data_inner_global_rating_avg(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        global_rating_weighted_avg = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_global_rating_weighted_avg.get_clanratings_top_200_response_oneOf_data_inner_global_rating_weighted_avg(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        efficiency = wot_api_client.models.get_clanratings_top_200_response_one_of_data_inner_efficiency.get_clanratings_top_200_response_oneOf_data_inner_efficiency(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        wins_ratio_avg = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_wins_ratio_avg.get_clanratings_clans_200_response_oneOf_data_value_wins_ratio_avg(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        rating_fort = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_rating_fort.get_clanratings_clans_200_response_oneOf_data_value_rating_fort(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        fb_elo_rating = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_fb_elo_rating.get_clanratings_clans_200_response_oneOf_data_value_fb_elo_rating(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        fb_elo_rating_10 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_fb_elo_rating_10.get_clanratings_clans_200_response_oneOf_data_value_fb_elo_rating_10(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        fb_elo_rating_8 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_fb_elo_rating_8.get_clanratings_clans_200_response_oneOf_data_value_fb_elo_rating_8(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        fb_elo_rating_6 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_fb_elo_rating_6.get_clanratings_clans_200_response_oneOf_data_value_fb_elo_rating_6(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        gm_elo_rating = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_gm_elo_rating.get_clanratings_clans_200_response_oneOf_data_value_gm_elo_rating(
                            value = 1.337, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        gm_elo_rating_10 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_gm_elo_rating_10.get_clanratings_clans_200_response_oneOf_data_value_gm_elo_rating_10(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        gm_elo_rating_8 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_gm_elo_rating_8.get_clanratings_clans_200_response_oneOf_data_value_gm_elo_rating_8(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        gm_elo_rating_6 = wot_api_client.models.get_clanratings_clans_200_response_one_of_data_value_gm_elo_rating_6.get_clanratings_clans_200_response_oneOf_data_value_gm_elo_rating_6(
                            value = 56, 
                            rank = 56, 
                            rank_delta = 56, ), 
                        exclude_reasons = {
                            'key' : ''
                            }, )
                    ],
        )
        """

    def testGetClanratingsTop200ResponseOneOf(self):
        """Test GetClanratingsTop200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
