# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_encyclopedia_vehicleprofiles200_response_one_of import GetEncyclopediaVehicleprofiles200ResponseOneOf

class TestGetEncyclopediaVehicleprofiles200ResponseOneOf(unittest.TestCase):
    """GetEncyclopediaVehicleprofiles200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEncyclopediaVehicleprofiles200ResponseOneOf:
        """Test GetEncyclopediaVehicleprofiles200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEncyclopediaVehicleprofiles200ResponseOneOf`
        """
        model = GetEncyclopediaVehicleprofiles200ResponseOneOf()
        if include_optional:
            return GetEncyclopediaVehicleprofiles200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = {
                    'key' : [
                        wot_api_client.models.get_encyclopedia_vehicleprofiles_200_response_one_of_data_value_inner.get_encyclopedia_vehicleprofiles_200_response_oneOf_data_value_inner(
                            profile_id = '', 
                            tank_id = 56, 
                            is_default = True, 
                            price_credit = 56, )
                        ]
                    }
            )
        else:
            return GetEncyclopediaVehicleprofiles200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_account_list_200_response_one_of_meta.get_account_list_200_response_oneOf_meta(
                    count = 56, ),
                data = {
                    'key' : [
                        wot_api_client.models.get_encyclopedia_vehicleprofiles_200_response_one_of_data_value_inner.get_encyclopedia_vehicleprofiles_200_response_oneOf_data_value_inner(
                            profile_id = '', 
                            tank_id = 56, 
                            is_default = True, 
                            price_credit = 56, )
                        ]
                    },
        )
        """

    def testGetEncyclopediaVehicleprofiles200ResponseOneOf(self):
        """Test GetEncyclopediaVehicleprofiles200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
