# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_globalmap_seasons200_response_one_of import GetGlobalmapSeasons200ResponseOneOf

class TestGetGlobalmapSeasons200ResponseOneOf(unittest.TestCase):
    """GetGlobalmapSeasons200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGlobalmapSeasons200ResponseOneOf:
        """Test GetGlobalmapSeasons200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGlobalmapSeasons200ResponseOneOf`
        """
        model = GetGlobalmapSeasons200ResponseOneOf()
        if include_optional:
            return GetGlobalmapSeasons200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_globalmap_seasons_200_response_one_of_meta.get_globalmap_seasons_200_response_oneOf_meta(
                    count = 56, 
                    page_total = 56, 
                    page = 56, ),
                data = [
                    wot_api_client.models.get_globalmap_seasons_200_response_one_of_data_inner.get_globalmap_seasons_200_response_oneOf_data_inner(
                        season_id = '', 
                        season_name = '', 
                        start = '', 
                        end = '', 
                        status = '', 
                        fronts = [
                            null
                            ], )
                    ]
            )
        else:
            return GetGlobalmapSeasons200ResponseOneOf(
                status = 'ok',
                meta = wot_api_client.models.get_globalmap_seasons_200_response_one_of_meta.get_globalmap_seasons_200_response_oneOf_meta(
                    count = 56, 
                    page_total = 56, 
                    page = 56, ),
                data = [
                    wot_api_client.models.get_globalmap_seasons_200_response_one_of_data_inner.get_globalmap_seasons_200_response_oneOf_data_inner(
                        season_id = '', 
                        season_name = '', 
                        start = '', 
                        end = '', 
                        status = '', 
                        fronts = [
                            null
                            ], )
                    ],
        )
        """

    def testGetGlobalmapSeasons200ResponseOneOf(self):
        """Test GetGlobalmapSeasons200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
