# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_clans_list200_response_one_of_meta import GetClansList200ResponseOneOfMeta

class TestGetClansList200ResponseOneOfMeta(unittest.TestCase):
    """GetClansList200ResponseOneOfMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClansList200ResponseOneOfMeta:
        """Test GetClansList200ResponseOneOfMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClansList200ResponseOneOfMeta`
        """
        model = GetClansList200ResponseOneOfMeta()
        if include_optional:
            return GetClansList200ResponseOneOfMeta(
                count = 56,
                total = 56
            )
        else:
            return GetClansList200ResponseOneOfMeta(
                count = 56,
                total = 56,
        )
        """

    def testGetClansList200ResponseOneOfMeta(self):
        """Test GetClansList200ResponseOneOfMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
