# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.encyclopedia_vehicles_data_value_default_profile_armor import EncyclopediaVehiclesDataValueDefaultProfileArmor

class TestEncyclopediaVehiclesDataValueDefaultProfileArmor(unittest.TestCase):
    """EncyclopediaVehiclesDataValueDefaultProfileArmor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EncyclopediaVehiclesDataValueDefaultProfileArmor:
        """Test EncyclopediaVehiclesDataValueDefaultProfileArmor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EncyclopediaVehiclesDataValueDefaultProfileArmor`
        """
        model = EncyclopediaVehiclesDataValueDefaultProfileArmor()
        if include_optional:
            return EncyclopediaVehiclesDataValueDefaultProfileArmor(
                hull = wot_api_client.models.encyclopedia_vehicles_data_value_default_profile_armor_hull.encyclopedia_vehicles_data_value_default_profile_armor_hull(
                    front = 56, 
                    sides = 56, 
                    rear = 56, ),
                turret = wot_api_client.models.encyclopedia_vehicles_data_value_default_profile_armor_turret.encyclopedia_vehicles_data_value_default_profile_armor_turret(
                    front = 56, 
                    sides = 56, 
                    rear = 56, )
            )
        else:
            return EncyclopediaVehiclesDataValueDefaultProfileArmor(
                hull = wot_api_client.models.encyclopedia_vehicles_data_value_default_profile_armor_hull.encyclopedia_vehicles_data_value_default_profile_armor_hull(
                    front = 56, 
                    sides = 56, 
                    rear = 56, ),
                turret = wot_api_client.models.encyclopedia_vehicles_data_value_default_profile_armor_turret.encyclopedia_vehicles_data_value_default_profile_armor_turret(
                    front = 56, 
                    sides = 56, 
                    rear = 56, ),
        )
        """

    def testEncyclopediaVehiclesDataValueDefaultProfileArmor(self):
        """Test EncyclopediaVehiclesDataValueDefaultProfileArmor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
