# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.get_clanratings_clans200_response_one_of_data_value_battles_count_avg import GetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg

class TestGetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg(unittest.TestCase):
    """GetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg:
        """Test GetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg`
        """
        model = GetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg()
        if include_optional:
            return GetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg(
                value = 1.337,
                rank = 56,
                rank_delta = 56
            )
        else:
            return GetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg(
                value = 1.337,
                rank = 56,
                rank_delta = 56,
        )
        """

    def testGetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg(self):
        """Test GetClanratingsClans200ResponseOneOfDataValueBattlesCountAvg"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
