# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.encyclopedia_modules_data_value import EncyclopediaModulesDataValue

class TestEncyclopediaModulesDataValue(unittest.TestCase):
    """EncyclopediaModulesDataValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EncyclopediaModulesDataValue:
        """Test EncyclopediaModulesDataValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EncyclopediaModulesDataValue`
        """
        model = EncyclopediaModulesDataValue()
        if include_optional:
            return EncyclopediaModulesDataValue(
                module_id = 56,
                type = '',
                name = '',
                price_credit = 56,
                image = '',
                weight = 56,
                tier = 56,
                nation = '',
                tanks = [
                    56
                    ],
                default_profile = wot_api_client.models.encyclopedia_modules_data_value_default_profile.encyclopedia_modules_data_value_default_profile(
                    gun = wot_api_client.models.encyclopedia_modules_data_value_default_profile_gun.encyclopedia_modules_data_value_default_profile_gun(
                        fire_rate = 1.337, 
                        dispersion = 1.337, 
                        aim_time = 1.337, 
                        reload_time = 1.337, 
                        move_up_arc = 56, 
                        move_down_arc = 56, 
                        traverse_speed = 56, 
                        ammo = [
                            wot_api_client.models.encyclopedia_vehicles_data_value_default_profile_ammo_inner.encyclopedia_vehicles_data_value_default_profile_ammo_inner(
                                type = '', 
                                damage = [
                                    56
                                    ], 
                                penetration = [
                                    56
                                    ], 
                                stun = wot_api_client.models.encyclopedia_vehicles_data_value_default_profile_ammo_inner_stun.encyclopedia_vehicles_data_value_default_profile_ammo_inner_stun(
                                    duration = wot_api_client.models.duration.duration(), ), )
                            ], 
                        max_ammo = 56, ), 
                    engine = wot_api_client.models.encyclopedia_modules_data_value_default_profile_engine.encyclopedia_modules_data_value_default_profile_engine(
                        power = 56, 
                        fire_chance = 1.337, ), 
                    turret = wot_api_client.models.encyclopedia_modules_data_value_default_profile_turret.encyclopedia_modules_data_value_default_profile_turret(
                        hp = 56, 
                        armor_front = 56, 
                        armor_sides = 56, 
                        armor_rear = 56, 
                        view_range = 56, 
                        traverse_speed = 56, ), 
                    suspension = wot_api_client.models.encyclopedia_modules_data_value_default_profile_suspension.encyclopedia_modules_data_value_default_profile_suspension(
                        load_limit = 56, 
                        traverse_speed = 56, ), 
                    radio = wot_api_client.models.encyclopedia_modules_data_value_default_profile_radio.encyclopedia_modules_data_value_default_profile_radio(
                        signal_range = 56, ), )
            )
        else:
            return EncyclopediaModulesDataValue(
                module_id = 56,
                type = '',
                name = '',
                price_credit = 56,
                image = '',
                weight = 56,
                tier = 56,
                nation = '',
                tanks = [
                    56
                    ],
        )
        """

    def testEncyclopediaModulesDataValue(self):
        """Test EncyclopediaModulesDataValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
