# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wot_api_client.models.account_list_ok import AccountListOk

class TestAccountListOk(unittest.TestCase):
    """AccountListOk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountListOk:
        """Test AccountListOk
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountListOk`
        """
        model = AccountListOk()
        if include_optional:
            return AccountListOk(
                status = 'ok',
                meta = wot_api_client.models.account_list_meta.account_list_meta(
                    count = 56, ),
                data = [
                    wot_api_client.models.account_list_data_inner.account_list_data_inner(
                        account_id = 56, 
                        nickname = '', )
                    ]
            )
        else:
            return AccountListOk(
                status = 'ok',
                meta = wot_api_client.models.account_list_meta.account_list_meta(
                    count = 56, ),
                data = [
                    wot_api_client.models.account_list_data_inner.account_list_data_inner(
                        account_id = 56, 
                        nickname = '', )
                    ],
        )
        """

    def testAccountListOk(self):
        """Test AccountListOk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
