# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wot_api_client.models.clans_accountinfo_data_value_clan import ClansAccountinfoDataValueClan
from typing import Optional, Set
from typing_extensions import Self

class ClansAccountinfoDataValue(BaseModel):
    """
    ClansAccountinfoDataValue
    """ # noqa: E501
    account_id: StrictInt = Field(description="Player account ID")
    account_name: StrictStr = Field(description="Player name")
    joined_at: StrictInt = Field(description="Date when player joined clan")
    role: StrictStr = Field(description="Technical position name")
    role_i18n: StrictStr = Field(description="Position")
    clan: Optional[ClansAccountinfoDataValueClan]
    __properties: ClassVar[List[str]] = ["account_id", "account_name", "joined_at", "role", "role_i18n", "clan"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClansAccountinfoDataValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of clan
        if self.clan:
            _dict['clan'] = self.clan.to_dict()
        # set to None if clan (nullable) is None
        # and model_fields_set contains the field
        if self.clan is None and "clan" in self.model_fields_set:
            _dict['clan'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClansAccountinfoDataValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_id": obj.get("account_id"),
            "account_name": obj.get("account_name"),
            "joined_at": obj.get("joined_at"),
            "role": obj.get("role"),
            "role_i18n": obj.get("role_i18n"),
            "clan": ClansAccountinfoDataValueClan.from_dict(obj["clan"]) if obj.get("clan") is not None else None
        })
        return _obj


