# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EncyclopediaVehiclesDataValueModulesTreeValue(BaseModel):
    """
    EncyclopediaVehiclesDataValueModulesTreeValue
    """ # noqa: E501
    module_id: StrictInt = Field(description="Module ID")
    name: StrictStr = Field(description="Module name")
    type: StrictStr = Field(description="Module type")
    price_credit: StrictInt = Field(description="Cost in credits")
    price_xp: StrictInt = Field(description="Research cost")
    next_tanks: Optional[List[StrictInt]] = Field(description="List of vehicle IDs available after research of the module")
    next_modules: Optional[List[StrictInt]] = Field(description="List of module IDs available after research of the module")
    is_default: StrictBool = Field(description="Indicates if the module is basic")
    __properties: ClassVar[List[str]] = ["module_id", "name", "type", "price_credit", "price_xp", "next_tanks", "next_modules", "is_default"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EncyclopediaVehiclesDataValueModulesTreeValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if next_tanks (nullable) is None
        # and model_fields_set contains the field
        if self.next_tanks is None and "next_tanks" in self.model_fields_set:
            _dict['next_tanks'] = None

        # set to None if next_modules (nullable) is None
        # and model_fields_set contains the field
        if self.next_modules is None and "next_modules" in self.model_fields_set:
            _dict['next_modules'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EncyclopediaVehiclesDataValueModulesTreeValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "module_id": obj.get("module_id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "price_credit": obj.get("price_credit"),
            "price_xp": obj.get("price_xp"),
            "next_tanks": obj.get("next_tanks"),
            "next_modules": obj.get("next_modules"),
            "is_default": obj.get("is_default")
        })
        return _obj


