# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetStrongholdClaninfo200ResponseOneOfDataValueBuildingSlotsInner(BaseModel):
    """
    GetStrongholdClaninfo200ResponseOneOfDataValueBuildingSlotsInner
    """ # noqa: E501
    position: StrictStr = Field(description="Position of the construction site")
    direction: StrictStr = Field(description="Bridgehead's name")
    arena_id: StrictStr = Field(description="Map ID associated with the current construction site")
    building_title: Optional[StrictStr] = Field(description="Name of the structure located on the current construction site")
    building_level: Optional[StrictInt] = Field(description="Level of the structure located on the current construction site")
    reserve_title: Optional[StrictStr] = Field(description="Name of the Reserve earned in the structure located on the current construction site")
    __properties: ClassVar[List[str]] = ["position", "direction", "arena_id", "building_title", "building_level", "reserve_title"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetStrongholdClaninfo200ResponseOneOfDataValueBuildingSlotsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if building_title (nullable) is None
        # and model_fields_set contains the field
        if self.building_title is None and "building_title" in self.model_fields_set:
            _dict['building_title'] = None

        # set to None if building_level (nullable) is None
        # and model_fields_set contains the field
        if self.building_level is None and "building_level" in self.model_fields_set:
            _dict['building_level'] = None

        # set to None if reserve_title (nullable) is None
        # and model_fields_set contains the field
        if self.reserve_title is None and "reserve_title" in self.model_fields_set:
            _dict['reserve_title'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetStrongholdClaninfo200ResponseOneOfDataValueBuildingSlotsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "position": obj.get("position"),
            "direction": obj.get("direction"),
            "arena_id": obj.get("arena_id"),
            "building_title": obj.get("building_title"),
            "building_level": obj.get("building_level"),
            "reserve_title": obj.get("reserve_title")
        })
        return _obj


