# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from wot_api_client.models.globalmap_provinces_error import GlobalmapProvincesError
from wot_api_client.models.globalmap_provinces_ok import GlobalmapProvincesOk
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

GETGLOBALMAPPROVINCES200RESPONSE_ONE_OF_SCHEMAS = ["GlobalmapProvincesError", "GlobalmapProvincesOk"]

class GetGlobalmapProvinces200Response(BaseModel):
    """
    GetGlobalmapProvinces200Response
    """
    # data type: GlobalmapProvincesOk
    oneof_schema_1_validator: Optional[GlobalmapProvincesOk] = None
    # data type: GlobalmapProvincesError
    oneof_schema_2_validator: Optional[GlobalmapProvincesError] = None
    actual_instance: Optional[Union[GlobalmapProvincesError, GlobalmapProvincesOk]] = None
    one_of_schemas: Set[str] = { "GlobalmapProvincesError", "GlobalmapProvincesOk" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = GetGlobalmapProvinces200Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: GlobalmapProvincesOk
        if not isinstance(v, GlobalmapProvincesOk):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GlobalmapProvincesOk`")
        else:
            match += 1
        # validate data type: GlobalmapProvincesError
        if not isinstance(v, GlobalmapProvincesError):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GlobalmapProvincesError`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in GetGlobalmapProvinces200Response with oneOf schemas: GlobalmapProvincesError, GlobalmapProvincesOk. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in GetGlobalmapProvinces200Response with oneOf schemas: GlobalmapProvincesError, GlobalmapProvincesOk. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("status")
        if not _data_type:
            raise ValueError("Failed to lookup data type from the field `status` in the input.")

        # check if data type is `GlobalmapProvincesError`
        if _data_type == "globalmap_provinces_error":
            instance.actual_instance = GlobalmapProvincesError.from_json(json_str)
            return instance

        # check if data type is `GlobalmapProvincesOk`
        if _data_type == "globalmap_provinces_ok":
            instance.actual_instance = GlobalmapProvincesOk.from_json(json_str)
            return instance

        # deserialize data into GlobalmapProvincesOk
        try:
            instance.actual_instance = GlobalmapProvincesOk.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GlobalmapProvincesError
        try:
            instance.actual_instance = GlobalmapProvincesError.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into GetGlobalmapProvinces200Response with oneOf schemas: GlobalmapProvincesError, GlobalmapProvincesOk. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GetGlobalmapProvinces200Response with oneOf schemas: GlobalmapProvincesError, GlobalmapProvincesOk. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], GlobalmapProvincesError, GlobalmapProvincesOk]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


