# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetGlobalmapEventaccountinfo200ResponseOneOfDataValueEventsValueInner(BaseModel):
    """
    GetGlobalmapEventaccountinfo200ResponseOneOfDataValueEventsValueInner
    """ # noqa: E501
    account_id: StrictInt = Field(description="Account ID")
    award_level: Optional[StrictStr] = Field(description="Award level")
    battles: StrictInt = Field(description="Battles fought for current clan")
    battles_to_award: StrictInt = Field(description="Battles to fight in a current clan to get clan award for the season")
    clan_id: StrictInt = Field(description="Clan ID")
    clan_rank: StrictInt = Field(description="Clan rating")
    event_id: StrictStr = Field(description="Event ID")
    fame_points: StrictInt = Field(description="Total Fame Points")
    fame_points_since_turn: StrictInt = Field(description="Change of Fame Points since last turn calculation")
    fame_points_to_improve_award: Optional[StrictInt] = Field(description="Amount of Fame Points needed to improve personal award")
    front_id: StrictStr = Field(description="Front ID")
    rank: Optional[StrictInt] = Field(description="Current rating")
    rank_delta: Optional[StrictInt] = Field(description="Rating changes during previous turn")
    updated_at: Optional[StrictInt] = Field(description="Date when account data were updated")
    url: Optional[StrictStr] = Field(description="Link to Front")
    __properties: ClassVar[List[str]] = ["account_id", "award_level", "battles", "battles_to_award", "clan_id", "clan_rank", "event_id", "fame_points", "fame_points_since_turn", "fame_points_to_improve_award", "front_id", "rank", "rank_delta", "updated_at", "url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGlobalmapEventaccountinfo200ResponseOneOfDataValueEventsValueInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if award_level (nullable) is None
        # and model_fields_set contains the field
        if self.award_level is None and "award_level" in self.model_fields_set:
            _dict['award_level'] = None

        # set to None if fame_points_to_improve_award (nullable) is None
        # and model_fields_set contains the field
        if self.fame_points_to_improve_award is None and "fame_points_to_improve_award" in self.model_fields_set:
            _dict['fame_points_to_improve_award'] = None

        # set to None if rank (nullable) is None
        # and model_fields_set contains the field
        if self.rank is None and "rank" in self.model_fields_set:
            _dict['rank'] = None

        # set to None if rank_delta (nullable) is None
        # and model_fields_set contains the field
        if self.rank_delta is None and "rank_delta" in self.model_fields_set:
            _dict['rank_delta'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGlobalmapEventaccountinfo200ResponseOneOfDataValueEventsValueInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_id": obj.get("account_id"),
            "award_level": obj.get("award_level"),
            "battles": obj.get("battles"),
            "battles_to_award": obj.get("battles_to_award"),
            "clan_id": obj.get("clan_id"),
            "clan_rank": obj.get("clan_rank"),
            "event_id": obj.get("event_id"),
            "fame_points": obj.get("fame_points"),
            "fame_points_since_turn": obj.get("fame_points_since_turn"),
            "fame_points_to_improve_award": obj.get("fame_points_to_improve_award"),
            "front_id": obj.get("front_id"),
            "rank": obj.get("rank"),
            "rank_delta": obj.get("rank_delta"),
            "updated_at": obj.get("updated_at"),
            "url": obj.get("url")
        })
        return _obj


