# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wot_api_client.models.get_encyclopedia_crewskills200_response_one_of_data_value_image_url import GetEncyclopediaCrewskills200ResponseOneOfDataValueImageUrl
from typing import Optional, Set
from typing_extensions import Self

class GetEncyclopediaCrewskills200ResponseOneOfDataValue(BaseModel):
    """
    GetEncyclopediaCrewskills200ResponseOneOfDataValue
    """ # noqa: E501
    skill: StrictStr = Field(description="Skill ID")
    name: Optional[StrictStr] = Field(description="Skill name")
    description: Optional[StrictStr] = Field(description="Skill description")
    image_url: Optional[GetEncyclopediaCrewskills200ResponseOneOfDataValueImageUrl]
    is_perk: StrictBool = Field(description="Indicates if it is a perk")
    __properties: ClassVar[List[str]] = ["skill", "name", "description", "image_url", "is_perk"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetEncyclopediaCrewskills200ResponseOneOfDataValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of image_url
        if self.image_url:
            _dict['image_url'] = self.image_url.to_dict()
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if image_url (nullable) is None
        # and model_fields_set contains the field
        if self.image_url is None and "image_url" in self.model_fields_set:
            _dict['image_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetEncyclopediaCrewskills200ResponseOneOfDataValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "skill": obj.get("skill"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "image_url": GetEncyclopediaCrewskills200ResponseOneOfDataValueImageUrl.from_dict(obj["image_url"]) if obj.get("image_url") is not None else None,
            "is_perk": obj.get("is_perk")
        })
        return _obj


