# coding: utf-8

"""
    World of Tanks

    OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer's room](https://developers.wargaming.net/).

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ace-tanker.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wot_api_client.models.stronghold_clanreserves_data_inner_in_stock_inner import StrongholdClanreservesDataInnerInStockInner
from typing import Optional, Set
from typing_extensions import Self

class StrongholdClanreservesDataInner(BaseModel):
    """
    StrongholdClanreservesDataInner
    """ # noqa: E501
    name: StrictStr = Field(description="Reserve name")
    type: StrictStr = Field(description="Reserve type")
    disposable: StrictBool = Field(description="Indicates if the Reserve is a One-Time-Effect Reserve")
    bonus_type: StrictStr = Field(description="Reserve efficiency type")
    icon: StrictStr = Field(description="URL to icon")
    in_stock: Optional[List[Optional[StrongholdClanreservesDataInnerInStockInner]]] = Field(description="Available clan Reserves and their status")
    __properties: ClassVar[List[str]] = ["name", "type", "disposable", "bonus_type", "icon", "in_stock"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StrongholdClanreservesDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in in_stock (list)
        _items = []
        if self.in_stock:
            for _item_in_stock in self.in_stock:
                if _item_in_stock:
                    _items.append(_item_in_stock.to_dict())
            _dict['in_stock'] = _items
        # set to None if in_stock (nullable) is None
        # and model_fields_set contains the field
        if self.in_stock is None and "in_stock" in self.model_fields_set:
            _dict['in_stock'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StrongholdClanreservesDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "disposable": obj.get("disposable"),
            "bonus_type": obj.get("bonus_type"),
            "icon": obj.get("icon"),
            "in_stock": [StrongholdClanreservesDataInnerInStockInner.from_dict(_item) for _item in obj["in_stock"]] if obj.get("in_stock") is not None else None
        })
        return _obj


